# Generated by Django 5.2.9 on 2026-01-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
